CC		:= cc
CFLAGS 	:= -O3 -flto
LDFLAGS := $(CFLAGS) -I/opt/homebrew/include -L/opt/homebrew/lib -Wl,-rpath,/opthomebrew/lib -lcurses -lcurl -ljson-c -lm
TARGET  := myapp
SRCDIR=src
BUILDDIR=src

all: $(TARGET)

$(TARGET):  
	$(BUILDDIR)/api.o $(BUILDDIR)/main.o $(BUILDDIR)/str.o $(BUILDDIR)/ui. $(BUILDDIR)/rc.o $(BUILDDIR)/stocks.o $(BUILDDIR)/state.o
	$(CC) $(CFLAGS) -o $^ $(LDFLAGS)

%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)
