CC		:= cc
INCLUDES	:= -I/opt/homebrew/Cellar/json-c/0.18/include/json-c \
-I/opt/homebrew/opt/ncurses/include \
-I/opt/homebrew/include 
CFLAGS 	:= -O2 $(INCLUDES)
LDFLAGS := $(CFLAGS) \
-L/opt/homebrew/Cellar/json-c/0.18/lib \
-L/opt/homebrew/opt/ncurses/lib \
-L/opt/homebrew/lib \
-Wl,-rpath,/opt/homebrew/lib \
-lcurses -lcurl -ljson-c -lm
TARGET  := myapp
SRCS    := $(wildcard src2/*.c)
OBJS    := $(patsubst %.c,%.o,$(SRCS))
all: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $(TARGET) 
  
#Based off of Makefile.2, unfortunately that version compiled but had a segmentation fault
# Was able to fix all compiler warnings by fixing api.c, (const char *), adding brew install ncurses to .yml, and 
# updating this makefile.5, however it still had a segmentation fault, so I suppose this program doesn't work. 
