CC		:= cc
CFLAGS 	:= -O3 -flto
LDFLAGS := $(CFLAGS) \
-I/opt/homebrew/Cellar/json-c/0.18/include -L/opt/homebrew/Cellar/json-c/0.18/lib \
-lcurses -lcurl -ljson-c -lm
TARGET  := myapp
SRCS    := $(wildcard src/*.c)
OBJS    := $(patsubst %.c,%.o,$(SRCS))
all: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $(TARGET) 
